# Generated by Django 4.1.7 on 2023-02-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='main', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parentmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu.menu')),
                ('parent', models.ForeignKey(default='main', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='menu.menu')),
            ],
        ),
    ]
